### PR TITLE
Update to jQuery 1.7 with new event API `.on()` and update jQuery Address foreign language URLs support on IE7 and IE6

### PR DESCRIPTION
**Pull request by laukstein**
Update to jQuery 1.7 with new event API `.on()` (do not forgot to add jQuery 1.7).
Update for jQuery Address foreign language URLs support on IE7 and IE6.

### CODE REVIEW

**Comment by asual** [comment]
Will this work if the plugin is used against older versions of jQuery?

**Comment by laukstein** [comment]
No, it will work just with jQuery 1.7 and later versions.
Anyway sooner or later you will need to do this switch since jQuery rewrite their APIs; read more in http://blog.jquery.com/2011/11/03/jquery-1-7-released/

**Comment by tristans** [comment]
Would like to note that this pull request works across all browsers I've tested (IE8,9, FF15, Chrome 22).

laukstein - this pull request has helped me; thank you for it. I hope you might reopen the pull request so asual may re-think the decision to not merge it.

**Comment by asual** [comment]
I'm not sure what is the benefit of this refactoring but the change sounds better now since we have a newer jQuery 1.8.

**Comment by tristans** [comment]
Live is deprecated, and it makes sense to switch to the new event API that jQuery provides.

**Comment by oomlaut** [comment]
What is the benefit (besides readability) of using `.on` instead of the `.bind` method?

**Comment by laukstein** [comment]
@oomlaut `.bind` is a deprecated jQuery syntax.

**Comment by oomlaut** [comment]
From the [jQuery API](http://api.jquery.com/bind/) `.on` may be preferred, however it is still a valid method, and has the benefit of being without much of the overhead of `.on`. Your documentation should note the incompatibilities and required revisions when working with versions prior to 1.7.

**Pull request closed without merging**
