### PR TITLE
IE7 issue for jquery.address.js and jQuery 1.5

### PR DESCRIPTION
**Pull request by laukstein**
Solved bug: IE7 non Latin character URL rewrite to gibberish on browser refresh.

### CODE REVIEW

**Comment by asual** [comment]
Are you sure that the following:
this.decode(_strict(_value)) = win[ID] !== UNDEFINED ? win[ID] : '';

should not be like this:
_value = win[ID] !== UNDEFINED ? decodeURI(win[ID]) : '';

**Comment by laukstein** [comment]
It works fine also with

```
_value = win[ID] !== UNDEFINED ? decode(win[ID]) : '';
```

but not with `decodeURI()`.

IE Webpage error details:

Message: Object expected
Line: 214
Char: 33
Code: 0
URI: jquery.address.js

Message: Exception thrown and not caught
Line: 16
Char: 39437
Code: 0
URI: jquery-1.5.min.js

**Comment by asual** [comment]
What happens if you use decodeURIComponent. The corresponding encodeURIComponent is used when the value is written in the IFRAME.

**Comment by laukstein** [comment]
Sorry, seems like I didn't clear fully browser cache before.
Works fine:

```
decodeURI(_value) = win[ID] !== UNDEFINED ? win[ID] : '';
```

Does not work:

```
_value = win[ID] !== UNDEFINED ? decodeURI(win[ID]) : '';
```

IE still reports the same jquery.address.js and jquery-1.5.min.js error.

**Comment by asual** [comment]
Lets not include jQuery 1.5 in this topic because it's a matter of another discussion.

```
decodeURI(_value) = win[ID] !== UNDEFINED ? win[ID] : '';
```

The above decodeURI() call is improper. You cannot execute functions like this on the left side of the assignment.

**Comment by laukstein** [comment]
This works fine:

```
 _value = win[ID] !== UNDEFINED ? decode(win[ID]) : '';
```

Will this be properer?

**Comment by asual** [comment]
Check the latest commit. Should work fine now.

**Comment by laukstein** [comment]
I check you latest commits.<br/>Unfortunately  `$.address.decode(win[ID])` does not work, it returns gibberish url.

With `$($.address).decode(win[ID])` and  `decode(win[ID])` it works fine, just IE gets error: _Object doesn't support this property or method_.

**Comment by asual** [comment]
It only works fine for you when you break the script. Unfortunately this is not an option.

**Comment by laukstein** [comment]
Hi Rostislav,

Try to add my commit laukstein/jquery-address@6895760c7369804404115705ebcfab261f8b5edf in your [repository](https://github.com/asual/jquery-address/blob/master/samples/state/data.xml); if you'll after try to open the non Latin URL on IE it will return urlencoded URL `%25D0%25BA%25D0%25BE%25D0%25BD%25D1%2582%25D0%25B0%25D0%25BA%25D1%2582%25D1%258D`. It appears even after your latest update `_value = win[ID] !== UNDEFINED ? $.address.decode(win[ID]) : '';`.

Do you have any issue to rewrite/decode it to UTF-8!?

**Comment by laukstein** [comment]
IE urldecode issue:
In line 132 change `encodeURIComponent(_href())` to `_href()` and change in your html/php inside $.ajax() change `event.path` to `encodeURIComponent(event.path)`.

**Pull request closed without merging**
